# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bibl_gui.ui'
#
# Created: Thu May 13 16:36:10 2010
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import psycopg2, pg
import ConfigParser

#настройки соединения с БД
config = ConfigParser.ConfigParser()
config.read('db_settings.cfg')

dbname = config.get('DatabaseConnect', 'dbname')
user = config.get('DatabaseConnect', 'user')
host = config.get('DatabaseConnect', 'host')
passwd = config.get('DatabaseConnect', 'password')
port=config.getint('DatabaseConnect', 'port')

class ExtLineEdit(object):
    """
    Этот класс включает в себя VBoxLayout, 
    в котором лежат LineEdit & ListView. Также здесь определяется ListModel,
    чтобы при создании объекта этого класса в нем было сразу все - 
    и строка ввода, и список автодополнения, и Модель списка и все что нужно для 
    нормальной работы автодополнений.

    тут же дописать про определение запросов для каждого объекта данного класса.
    описания классов и ф-й брать из test.py, auto.py
    """
    
    def setupUi(self, Elem):
        Elem.setObjectName("Elem")
        Elem.resize(280, 133)
        self.verticalLayout = QtGui.QVBoxLayout(Elem)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtGui.QLineEdit(Elem)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.listView = QtGui.QListView(Elem)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.verticalLayout.setContentsMargins(0,0,0,0)
        self.verticalLayout.setSpacing(0)
        #self.listView.hide()

        self.retranslateUi(Elem)
        QtCore.QMetaObject.connectSlotsByName(Elem)



    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))


#Этот класс - чтобы было удобнее вставлять объекты прямо в форму.
class ExtLine(QtGui.QWidget, ExtLineEdit):
    def __init__(self, *args):
        QtGui.QWidget.__init__(self)
        
        #Второе соединение с базой... 
        self.conn = psycopg2.connect("dbname='%s' user='%s' host='%s'  password='%s' port=%d" % (dbname, user, host, passwd, port))
        self.cur = self.conn.cursor()
        self.setupUi(self)
        self.query = args[0]
        self.words = []
        self.listModel = ListModel(self, self.words)
        self.listView.setModel(self.listModel)
        self.listView.hide()
        
        self.connect(self.lineEdit, QtCore.SIGNAL("textChanged(QString)"), self.print_text)
        self.connect(self.listView, QtCore.SIGNAL("activated(QModelIndex)"), self.set_text)

    def set_text(self):
        prev_string = unicode(self.lineEdit.text())

        prev_list = prev_string.split(",")
        del(prev_list[-1])
        prev_string = ",".join(prev_list)
        list_string = unicode(self.listView.currentIndex().data().toString())
        fut_string = []
        fut_string.append([prev_string, list_string])
        #print fut_string
        #print prev_string, self.listView.currentIndex().data().toString()
        if len(prev_string) > 1:
            self.lineEdit.setText(prev_string + ", " + list_string)# + self.listView.currentIndex().data().toString().lstrip(prev_string))
        else:
            self.lineEdit.setText(list_string)

        #print self.listView.currentIndex().data().toString()
        self.listModel.setAllData([])
        self.listView.hide()
        self.lineEdit.setFocus()

    #Осуществляет поиск последнего введенного слова
    def print_text(self):

        self.words.append(self.lineEdit.text())
        if len(self.lineEdit.text()) > 0:

            a = unicode(self.lineEdit.text()).split(",")
            for i in xrange(len(a)):
                a[i] = a[i].replace(" ", "")
                if len(a[i]) == 0:
                    del a[i]


            self.cur.execute(self.query % pg.escape_string(a[-1].encode("utf-8")))
            rest = []
            for i in xrange(self.cur.rowcount):
                rest.append(self.cur.fetchone()[0].decode("utf-8"))
            if len(rest) > 0:
                self.listView.show()
                rest.sort()
                self.listModel.setAllData(rest)
                if rest[-1] == a[-1]:
                    #self.lineEdit.setText(rest[0])
                    self.listView.hide()
            else:
                self.listView.hide()
        else:
            self.listView.hide()



class ListModel(QtCore.QAbstractListModel):
    def __init__(self, parent, words, *args):
        QtCore.QAbstractListModel.__init__(self, parent, *args)
        self.words = []

    def rowCount(self, parent=QtCore.QModelIndex()):
        return len(self.words)

    def data(self, index, role):

        if index.isValid() and role == QtCore.Qt.DisplayRole:
            return QtCore.QVariant(self.words[index.row()])
        else:
            return QtCore.QVariant()

    def setAllData(self, new_list):
        self.words = new_list
        self.reset()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550,420)
        MainWindow.setMinimumSize(QtCore.QSize(0,0))
        MainWindow.setDockOptions(QtGui.QMainWindow.ForceTabbedDocks)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tableWidget = QtGui.QTableWidget(self.centralwidget)
        self.tableWidget.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setSortingEnabled(True)
        self.tableWidget.setObjectName("tableWidget")
        self.horizontalLayout_3.addWidget(self.tableWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0,0,841,18))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtGui.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_edit = QtGui.QMenu(self.menubar)
        self.menu_edit.setObjectName("menu_edit")
        self.menu_search = QtGui.QMenu(self.menubar)
        self.menu_search.setObjectName("menu_search")
        self.menu_help = QtGui.QMenu(self.menubar)
        self.menu_help.setObjectName("menu_help")
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setAcceptDrops(False)
        self.toolBar.setAutoFillBackground(True)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea,self.toolBar)

        self.resultsDock = QtGui.QDockWidget(MainWindow)
        self.resultsDock.setObjectName("resultsDock")
        self.resultsDockContents = QtGui.QWidget(self.resultsDock)
        self.resultsDockContents.setObjectName("resultsDockContents")
        self.resulthorizontalLayout = QtGui.QHBoxLayout(self.resultsDockContents)
        self.resulthorizontalLayout.setObjectName("resulthorizontalLayout")
        self.resultTextBrowser = QtGui.QTextEdit(self.resultsDockContents)
        self.resultTextBrowser.setReadOnly(True)
        self.resultTextBrowser.setAutoFormatting(QtGui.QTextEdit.AutoAll)
        self.resultTextBrowser.setObjectName("resultTextBrowser")
        self.resulthorizontalLayout.addWidget(self.resultTextBrowser)
        self.resultsDock.setWidget(self.resultsDockContents)

        self.abstractDock = QtGui.QDockWidget(MainWindow)
        self.abstractDock.setObjectName("abstractDock")
        self.dockWidgetContents_2 = QtGui.QWidget(self.abstractDock)
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.dockWidgetContents_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        
        #self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents_2)
        
        self.textBrowser = QtGui.QTextEdit(self.dockWidgetContents_2)
        self.textBrowser.setReadOnly(True)
        self.textBrowser.setAutoFormatting(QtGui.QTextEdit.AutoAll)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_2.addWidget(self.textBrowser)
        self.abstractDock.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8),self.abstractDock)
        self.add_dataDOCK = QtGui.QDockWidget(MainWindow)
    
        self.add_dataDOCK.setObjectName("add_dataDOCK")
        self.add_dataDOCK.setWindowTitle(u'Добавление данных')
        self.dockWidgetContents = QtGui.QWidget(self.add_dataDOCK)
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtGui.QScrollArea(self.dockWidgetContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrolladd = QtGui.QWidget(self.scrollArea)
        self.scrolladd.setGeometry(QtCore.QRect(0,-1755,396,1983))
        self.scrolladd.setObjectName("scrolladd")
        self.verticalLayout_4 = QtGui.QGridLayout(self.scrolladd)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_10 = QtGui.QLabel(self.scrolladd)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)


        
        self.lineEdit_authors = ExtLine("""select name from authors where name ilike '%s%%'""")
        #QtGui.QLineEdit(self.scrolladd)
        self.lineEdit_authors.setObjectName("lineEdit_authors")
        self.verticalLayout_4.addWidget(self.lineEdit_authors)
        
        


        self.label_36 = QtGui.QLabel(self.scrolladd)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_4.addWidget(self.label_36)
        self.lineEdit_name_orig = QtGui.QLineEdit(self.scrolladd)
        self.lineEdit_name_orig.setObjectName("lineEdit_name_orig")
        self.verticalLayout_4.addWidget(self.lineEdit_name_orig)
        self.label_38 = QtGui.QLabel(self.scrolladd)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_4.addWidget(self.label_38)
        self.lineEdit_name_alt = QtGui.QLineEdit(self.scrolladd)
        self.lineEdit_name_alt.setObjectName("lineEdit_name_alt")
        self.verticalLayout_4.addWidget(self.lineEdit_name_alt)
        self.label_13 = QtGui.QLabel(self.scrolladd)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_4.addWidget(self.label_13)
        self.lineEdit_year = QtGui.QLineEdit(self.scrolladd)
        self.lineEdit_year.setObjectName("lineEdit_year")
        self.verticalLayout_4.addWidget(self.lineEdit_year)
        self.label_40 = QtGui.QLabel(self.scrolladd)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_4.addWidget(self.label_40)
        

        self.lineEdit_source = ExtLine("""select distinct source from articles where source ilike '%s%%'""")
        self.lineEdit_source.setObjectName("lineEdit_source")
        self.verticalLayout_4.addWidget(self.lineEdit_source)
        
        


        self.label_41 = QtGui.QLabel(self.scrolladd)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_4.addWidget(self.label_41)
        
        
        self.lineEdit_publisher = ExtLine("""select publisher from publ where publisher ilike '%s%%'""")
        self.lineEdit_publisher.setObjectName("lineEdit_publisher")
        self.verticalLayout_4.addWidget(self.lineEdit_publisher)
        

        self.label_20 = QtGui.QLabel(self.scrolladd)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_4.addWidget(self.label_20)


        self.lineEdit_publ_place = ExtLine("""select location from publ_location where location ilike '%s%%'""")
        self.lineEdit_publ_place.setObjectName("lineEdit_publ_place")
        self.verticalLayout_4.addWidget(self.lineEdit_publ_place)


        self.label_37 = QtGui.QLabel(self.scrolladd)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_4.addWidget(self.label_37)

        self.lineEdit_editors = ExtLine("""select editor from editor where editor ilike '%s%%'""")
        self.lineEdit_editors.setObjectName("lineEdit_editors")
        self.verticalLayout_4.addWidget(self.lineEdit_editors)

        self.label_11 = QtGui.QLabel(self.scrolladd)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.lineEdit_vol = QtGui.QLineEdit(self.scrolladd)
        self.lineEdit_vol.setObjectName("lineEdit_vol")
        self.verticalLayout_4.addWidget(self.lineEdit_vol)
        self.label_9 = QtGui.QLabel(self.scrolladd)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.lineEdit_number = QtGui.QLineEdit(self.scrolladd)
        self.lineEdit_number.setObjectName("lineEdit_number")
        self.verticalLayout_4.addWidget(self.lineEdit_number)
        self.label_39 = QtGui.QLabel(self.scrolladd)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_4.addWidget(self.label_39)
        self.lineEdit_issue = QtGui.QLineEdit(self.scrolladd)
        self.lineEdit_issue.setObjectName("lineEdit_issue")
        self.verticalLayout_4.addWidget(self.lineEdit_issue)
        self.label_14 = QtGui.QLabel(self.scrolladd)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_4.addWidget(self.label_14)
        self.lineEdit_series = QtGui.QLineEdit(self.scrolladd)
        self.lineEdit_series.setObjectName("lineEdit_series")
        self.verticalLayout_4.addWidget(self.lineEdit_series)
        self.label_48 = QtGui.QLabel(self.scrolladd)
        self.label_48.setObjectName("label_48")
        self.verticalLayout_4.addWidget(self.label_48)
        self.lineEdit_part = QtGui.QLineEdit(self.scrolladd)
        self.lineEdit_part.setObjectName("lineEdit_part")
        self.verticalLayout_4.addWidget(self.lineEdit_part)
        self.label_42 = QtGui.QLabel(self.scrolladd)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_4.addWidget(self.label_42)
        self.lineEdit_pages = QtGui.QLineEdit(self.scrolladd)
        self.lineEdit_pages.setObjectName("lineEdit_pages")
        self.verticalLayout_4.addWidget(self.lineEdit_pages)
        self.label_51 = QtGui.QLabel(self.scrolladd)
        self.label_51.setObjectName("label_51")
        self.verticalLayout_4.addWidget(self.label_51)
        self.lineEdit_tables = QtGui.QLineEdit(self.scrolladd)
        self.lineEdit_tables.setObjectName("lineEdit_tables")
        self.verticalLayout_4.addWidget(self.lineEdit_tables)
        self.label_16 = QtGui.QLabel(self.scrolladd)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_4.addWidget(self.label_16)
        self.lineEdit_maps = QtGui.QLineEdit(self.scrolladd)
        self.lineEdit_maps.setObjectName("lineEdit_maps")
        self.verticalLayout_4.addWidget(self.lineEdit_maps)
        self.label_12 = QtGui.QLabel(self.scrolladd)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_4.addWidget(self.label_12)
        self.lineEdit_ill = QtGui.QLineEdit(self.scrolladd)
        self.lineEdit_ill.setObjectName("lineEdit_ill")
        self.verticalLayout_4.addWidget(self.lineEdit_ill)
        self.label_54 = QtGui.QLabel(self.scrolladd)
        self.label_54.setObjectName("label_54")
        self.verticalLayout_4.addWidget(self.label_54)
        self.lineEdit_publ_numb = QtGui.QLineEdit(self.scrolladd)
        self.lineEdit_publ_numb.setObjectName("lineEdit_publ_numb")
        self.verticalLayout_4.addWidget(self.lineEdit_publ_numb)
        self.label_43 = QtGui.QLabel(self.scrolladd)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_4.addWidget(self.label_43)
        self.lineEdit_zool_rec = QtGui.QLineEdit(self.scrolladd)
        self.lineEdit_zool_rec.setObjectName("lineEdit_zool_rec")
        self.verticalLayout_4.addWidget(self.lineEdit_zool_rec)
        self.label_44 = QtGui.QLabel(self.scrolladd)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_4.addWidget(self.label_44)
        self.lineEdit_series_area = QtGui.QLineEdit(self.scrolladd)
        self.lineEdit_series_area.setObjectName("lineEdit_series_area")
        self.verticalLayout_4.addWidget(self.lineEdit_series_area)
        self.label_45 = QtGui.QLabel(self.scrolladd)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_4.addWidget(self.label_45)
        self.lineEdit_publ_lang = QtGui.QLineEdit(self.scrolladd)
        self.lineEdit_publ_lang.setObjectName("lineEdit_publ_lang")
        self.verticalLayout_4.addWidget(self.lineEdit_publ_lang)
        self.listView_publ_lang= QtGui.QListView()
        self.listView_publ_lang.setObjectName("listView_publ_lang")
        self.verticalLayout_4.addWidget(self.listView_publ_lang)
        self.listView_publ_lang.hide()



        self.label_6 = QtGui.QLabel(self.scrolladd)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)


        self.lineEdit_publ_country = ExtLine("""select publ_country from articles where publ_country ilike '%s%%'""")
        self.lineEdit_publ_country.setObjectName("lineEdit_publ_country")
        self.verticalLayout_4.addWidget(self.lineEdit_publ_country)


        self.label_15 = QtGui.QLabel(self.scrolladd)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_4.addWidget(self.label_15)

        self.lineEdit_publ_type = ExtLine("""select distinct type from articles where type ilike '%s%%'""")
        self.lineEdit_publ_type.setObjectName("lineEdit_publ_type")
        self.verticalLayout_4.addWidget(self.lineEdit_publ_type)



        self.label_7 = QtGui.QLabel(self.scrolladd)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.lineEdit_num_ed_mpk = QtGui.QLineEdit(self.scrolladd)
        self.lineEdit_num_ed_mpk.setObjectName("lineEdit_num_ed_mpk")
        self.verticalLayout_4.addWidget(self.lineEdit_num_ed_mpk)
        self.label_53 = QtGui.QLabel(self.scrolladd)
        self.label_53.setObjectName("label_53")
        self.verticalLayout_4.addWidget(self.label_53)
        self.lineEdit_main_ind_mpk = QtGui.QLineEdit(self.scrolladd)
        self.lineEdit_main_ind_mpk.setObjectName("lineEdit_main_ind_mpk")
        self.verticalLayout_4.addWidget(self.lineEdit_main_ind_mpk)
        self.label_8 = QtGui.QLabel(self.scrolladd)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.lineEdit_pat_owner = QtGui.QLineEdit(self.scrolladd)
        self.lineEdit_pat_owner.setObjectName("lineEdit_pat_owner")
        self.verticalLayout_4.addWidget(self.lineEdit_pat_owner)
        self.label_46 = QtGui.QLabel(self.scrolladd)
        self.label_46.setObjectName("label_46")
        self.add_dataDOCK.setWidget(self.dockWidgetContents)
        #MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8),self.add_dataDOCK)
        self.verticalLayout_4.addWidget(self.label_46)
        self.lineEdit_publ_number = QtGui.QLineEdit(self.scrolladd)
        self.lineEdit_publ_number.setObjectName("lineEdit_publ_number")
        self.verticalLayout_4.addWidget(self.lineEdit_publ_number)
        self.label_49 = QtGui.QLabel(self.scrolladd)
        self.label_49.setObjectName("label_49")
        self.verticalLayout_4.addWidget(self.label_49)
        self.dateEdit_publ_date = QtGui.QDateEdit(self.scrolladd)
        self.dateEdit_publ_date.setObjectName("dateEdit_publ_date")
        self.verticalLayout_4.addWidget(self.dateEdit_publ_date)
        self.label = QtGui.QLabel(self.scrolladd)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.lineEdit_ref_code = QtGui.QLineEdit(self.scrolladd)
        self.lineEdit_ref_code.setObjectName("lineEdit_ref_code")
        self.verticalLayout_4.addWidget(self.lineEdit_ref_code)
        self.label_2 = QtGui.QLabel(self.scrolladd)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.lineEdit_udk = QtGui.QLineEdit(self.scrolladd)
        self.lineEdit_udk.setObjectName("lineEdit_udk")
        self.verticalLayout_4.addWidget(self.lineEdit_udk)
        self.label_4 = QtGui.QLabel(self.scrolladd)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.lineEdit_issn = QtGui.QLineEdit(self.scrolladd)
        self.lineEdit_issn.setObjectName("lineEdit_issn")
        self.verticalLayout_4.addWidget(self.lineEdit_issn)
        self.label_5 = QtGui.QLabel(self.scrolladd)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.lineEdit_isbn = QtGui.QLineEdit(self.scrolladd)
        self.lineEdit_isbn.setObjectName("lineEdit_isbn")
        self.verticalLayout_4.addWidget(self.lineEdit_isbn)


        self.fileWidget = QtGui.QWidget()
        self.verticalLayout_4.addWidget(self.fileWidget)
        
        self.fileWidgetLayout = QtGui.QGridLayout(self.fileWidget)
        self.fileWidgetLayout.setContentsMargins(0, 0, 0, 0)

        self.label_17 = QtGui.QLabel(self.scrolladd)
        self.label_17.setObjectName("label_17")
        self.fileWidgetLayout.addWidget(self.label_17)

        self.lineEdit_file_path = QtGui.QLineEdit(self.scrolladd)
        self.lineEdit_file_path.setObjectName("lineEdit_file_path")
        self.fileWidgetLayout.addWidget(self.lineEdit_file_path)
        
        self.pushButton_file_path = QtGui.QPushButton()
        self.pushButton_file_path.setObjectName("pushButton_file_path")
        self.pushButton_file_path.setText(u"Добавить")
        self.fileWidgetLayout.addWidget(self.pushButton_file_path, 1, 1)
        
        self.label_18 = QtGui.QLabel(self.scrolladd)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_4.addWidget(self.label_18)


        self.lineEdit_comm_keywds = ExtLine("""select words from keywords where words ilike '%s%%'""")
        self.lineEdit_comm_keywds.setObjectName("lineEdit_comm_keywds")
        self.verticalLayout_4.addWidget(self.lineEdit_comm_keywds)


        self.label_19 = QtGui.QLabel(self.scrolladd)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_4.addWidget(self.label_19)


        self.lineEdit_taxon_keywds = ExtLine("""select distinct taxon_keywords from articles where taxon_keywords ilike '%s%%'""")
        self.lineEdit_taxon_keywds.setObjectName("lineEdit_taxon_keywds")
        self.verticalLayout_4.addWidget(self.lineEdit_taxon_keywds)


        self.label_52 = QtGui.QLabel(self.scrolladd)
        self.label_52.setObjectName("label_52")
        self.verticalLayout_4.addWidget(self.label_52)
        self.textEdit_abstract = QtGui.QTextEdit(self.scrolladd)
        self.textEdit_abstract.setObjectName("textEdit_abstract")
        self.verticalLayout_4.addWidget(self.textEdit_abstract)
        self.buttonBox_add_entry = QtGui.QDialogButtonBox(self.scrolladd)
        self.buttonBox_add_entry.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_add_entry.setObjectName("buttonBox_add_entry")
        self.verticalLayout_4.addWidget(self.buttonBox_add_entry)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.scrollArea.setWidget(self.scrolladd)
        self.add_dataDOCK.setWidget(self.dockWidgetContents)
        #Это добавляет док справа. 8-снизу, 1-сверху
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2),self.add_dataDOCK)
        self.abstractDock.setWindowTitle(u"Стандартный вид")
        self.resultsDock.setWindowTitle(u"Совпадения")

        #Это объединяет доки во вкладки.
        MainWindow.tabifyDockWidget(self.abstractDock, self.resultsDock)
        self.abstractDock.raise_()
        
        self.create = QtGui.QAction(MainWindow)
        self.create.setObjectName("create")
        create_icon = QtGui.QIcon()
        create_icon.addPixmap(QtGui.QPixmap("icons/calendar_add.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.create.setIcon(create_icon)

        self.open_ = QtGui.QAction(MainWindow)
        open_icon = QtGui.QIcon()
        open_icon.addPixmap(QtGui.QPixmap("icons/database_connect.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        #self.create.setIcon(icon)
        self.open_.setIcon(open_icon)
        self.open_.setObjectName("open_")
        self.close = QtGui.QAction(MainWindow)
        self.close.setObjectName("close")
        close_icon = QtGui.QIcon()
        close_icon.addPixmap(QtGui.QPixmap("icons/database_delete.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.close.setIcon(close_icon)

        self.save = QtGui.QAction(MainWindow)
        self.save.setObjectName("save")
        save_icon = QtGui.QIcon()
        save_icon.addPixmap(QtGui.QPixmap("icons/database_save.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.save.setIcon(save_icon)

        self.save_as = QtGui.QAction(MainWindow)
        self.save_as.setObjectName("save_as")
        self.save_as.setIcon(save_icon)

        self.del_ = QtGui.QAction(MainWindow)
        self.del_.setObjectName("del_")
        delete_icon = QtGui.QIcon()
        delete_icon.addPixmap(QtGui.QPixmap("icons/delete.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.del_.setIcon(delete_icon)

        self.dumpall = QtGui.QAction(MainWindow)
        self.dumpall.setObjectName('dumpall')
        dumpall_icon = QtGui.QIcon()
        dumpall_icon.addPixmap(QtGui.QPixmap("icons/database_refresh.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.dumpall.setIcon(dumpall_icon)


        self.write_in = QtGui.QAction(MainWindow)
        self.write_in.setObjectName("write_in")
        export_icon = QtGui.QIcon()
        export_icon.addPixmap(QtGui.QPixmap("icons/arrow-180.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.write_in.setIcon(export_icon)

        self.concatenate = QtGui.QAction(MainWindow)
        self.concatenate.setObjectName("concatenate")
        concat_icon = QtGui.QIcon()
        concat_icon.addPixmap(QtGui.QPixmap("icons/arrow-join.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.concatenate.setIcon(concat_icon)

        self.write_from = QtGui.QAction(MainWindow)
        self.write_from.setObjectName("write_from")
        import_icon = QtGui.QIcon()
        import_icon.addPixmap(QtGui.QPixmap("icons/arrow.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.write_from.setIcon(import_icon)

        self.sort_ = QtGui.QAction(MainWindow)
        self.sort_.setObjectName("sort_")
        sort_icon = QtGui.QIcon()
        sort_icon.addPixmap(QtGui.QPixmap("icons/table_sort.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.sort_.setIcon(sort_icon)

        
        self.print_ = QtGui.QAction(MainWindow)
        self.print_.setObjectName("print_")
        print_icon = QtGui.QIcon()
        print_icon.addPixmap(QtGui.QPixmap("icons/printer.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.print_.setIcon(print_icon)

        self.exit_ = QtGui.QAction(MainWindow)
        self.exit_.setObjectName("exit_")


        self.undo = QtGui.QAction(MainWindow)
        self.undo.setObjectName("undo")
        undo_icon = QtGui.QIcon()
        undo_icon.addPixmap(QtGui.QPixmap("icons/arrow_undo.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.undo.setIcon(undo_icon)

        self.undo_query = QtGui.QAction(MainWindow)
        self.undo_query.setObjectName("undo_query")
        
        self.query_list = QtGui.QAction(MainWindow)
        self.query_list.setObjectName("query_list")

        self.save_result = QtGui.QAction(MainWindow)
        self.save_result.setObjectName("save_result")
        

        self.redo = QtGui.QAction(MainWindow)
        self.redo.setObjectName("redo")
        redo_icon = QtGui.QIcon()
        redo_icon.addPixmap(QtGui.QPixmap("icons/arrow_redo.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.redo.setIcon(redo_icon)

        self.redo_query = QtGui.QAction(MainWindow)
        self.redo_query.setObjectName("redo_query")
        
        

        self.copy = QtGui.QAction(MainWindow)
        self.copy.setObjectName("copy")
        self.crop = QtGui.QAction(MainWindow)
        self.crop.setObjectName("crop")
        self.insert = QtGui.QAction(MainWindow)
        self.insert.setObjectName("insert")
        self.select_all = QtGui.QAction(MainWindow)
        self.select_all.setObjectName("select_all")
        self.undo_all = QtGui.QAction(MainWindow)
        self.undo_all.setObjectName("undo_all")
        #self.search_all = QtGui.QAction(MainWindow)
        #self.search_all.setObjectName("search_all")
        self.searchCompl = QtGui.QAction(MainWindow)
        self.searchCompl.setObjectName("searchCompl")
        self.searchKw = QtGui.QAction(MainWindow)
        self.searchKw.setObjectName("searchKw")
        #self.searchTaxKw = QtGui.QAction(MainWindow)
        #self.searchTaxKw.setObjectName("searchTaxKw")
        self.help = QtGui.QAction(MainWindow)
        self.help.setObjectName("help")
        self.about = QtGui.QAction(MainWindow)
        self.about.setObjectName("about")

        self.report_error = QtGui.QAction(MainWindow)
        self.report_error.setObjectName("report_error")

        self.database_info = QtGui.QAction(MainWindow)
        self.database_info.setObjectName("database_info")
        self.toolBarHome = QtGui.QAction(MainWindow)
        self.toolBarHome.setObjectName("toolBarHome")
        
        self.toolBarPrev = QtGui.QAction(MainWindow)
        self.toolBarPrev.setObjectName("toolBarPrev")

        searchIcon = QtGui.QIcon()
        searchIcon.addPixmap(QtGui.QPixmap("icons/search_icon.gif"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.toolBarPrev.setIcon(searchIcon)

        self.toolBarNext = QtGui.QAction(MainWindow)
        self.toolBarNext.setObjectName("toolBarNext")
        self.toolBarEnd = QtGui.QAction(MainWindow)
        self.toolBarEnd.setObjectName("toolBarEnd")
        self.toolBarOpenDatabase = QtGui.QAction(MainWindow)
        self.toolBarOpenDatabase.setObjectName("toolBarOpenDatabase")
        self.toolBarOpenDatabase.setIcon(open_icon)
        self.toolBarCloseDatabase = QtGui.QAction(MainWindow)
        self.toolBarCloseDatabase.setObjectName("toolBarCloseDatabase")
        self.toolBarCloseDatabase.setIcon(close_icon)
        self.toolBarNewEntry = QtGui.QAction(MainWindow)
        self.toolBarNewEntry.setObjectName("toolBarNewEntry")
        self.toolBarDeleteEntry = QtGui.QAction(MainWindow)
        self.toolBarDeleteEntry.setObjectName("toolBarDeleteEntry")
        self.toolBarEditEntry = QtGui.QAction(MainWindow)
        self.toolBarEditEntry.setObjectName("toolBarEditEntry")
        self.toolBarSimpleSearch = QtGui.QAction(MainWindow)
        self.toolBarSimpleSearch.setObjectName("toolBarSimpleSearch")
        self.preferences = QtGui.QAction(MainWindow)
        self.preferences.setObjectName("preferences")
        self.toolBarUndo = QtGui.QAction(MainWindow)
        self.toolBarUndo.setObjectName("toolBarUndo")
        self.toolBarReset = QtGui.QAction(MainWindow)
        self.toolBarReset.setObjectName("toolBarReset")
        self.searchFulltext = QtGui.QAction(MainWindow)
        self.searchFulltext.setObjectName("searchFulltext")
        self.searchDupl = QtGui.QAction(MainWindow)
        self.searchDupl.setObjectName("searchDupl")
        self.toolBarCommit = QtGui.QAction(MainWindow)
        self.toolBarCommit.setObjectName("toolBarCommit")
        self.action_dfg = QtGui.QAction(MainWindow)
        self.action_dfg.setObjectName("action_dfg")
        self.action_asd = QtGui.QAction(MainWindow)
        self.action_asd.setObjectName("action_asd")
        self.action_sdf = QtGui.QAction(MainWindow)
        self.action_sdf.setObjectName("action_sdf")
        self.action_sdf_2 = QtGui.QAction(MainWindow)
        self.action_sdf_2.setObjectName("action_sdf_2")
        self.actionDfg = QtGui.QAction(MainWindow)
        self.actionDfg.setObjectName("actionDfg")
        self.action_dfgh = QtGui.QAction(MainWindow)
        self.action_dfgh.setObjectName("action_dfgh")
        self.action_hgf = QtGui.QAction(MainWindow)
        self.action_hgf.setObjectName("action_hgf")
        self.action_aaa = QtGui.QAction(MainWindow)
        self.action_aaa.setObjectName("action_aaa")
        self.actionJapan = QtGui.QAction(MainWindow)
        self.actionJapan.setObjectName("actionJapan")

        self.action_home = QtGui.QAction(MainWindow)
        self.action_home.setObjectName("action_home")
        home_icon = QtGui.QIcon()
        home_icon.addPixmap(QtGui.QPixmap("icons/application_home.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.action_home.setIcon(home_icon)

        self.toolBarHome.setIcon(home_icon)
        
        self.action_7 = QtGui.QAction(MainWindow)
      
        #чтобы в меню можно было ставить галочки 
        #напротив пунктов, но нам это не надо
        #self.action_7.setCheckable(True)
        #self.action_7.setChecked(True)
        
        
        self.action_7.setObjectName("action_7")
        self.action_8 = QtGui.QAction(MainWindow)
        self.action_8.setObjectName("action_8")
        #self.action_8.setCheckable(True)

        self.action_9 = QtGui.QAction(MainWindow)
        self.action_9.setObjectName("action_9")
        #self.action_9.setCheckable(True)

        self.action_10 = QtGui.QAction(MainWindow)
        self.action_10.setObjectName("action_10")
        #self.action_10.setCheckable(True)
        #self.menu_file.addAction(self.create)
        #self.menu_file.addAction(self.open_)
        #self.menu_file.addAction(self.close)
        #self.menu_file.addSeparator()
        self.menu_file.addAction(self.save)
        #self.menu_file.addAction(self.save_as)
        self.menu_file.addAction(self.del_)
        self.menu_file.addAction(self.dumpall)
        self.menu_file.addAction(self.write_in)
        #self.menu_file.addAction(self.concatenate)
        self.menu_file.addAction(self.write_from)
        #self.menu_file.addAction(self.sort_)
        
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.print_)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.exit_)
        self.menu_edit.addAction(self.undo)
        self.menu_edit.addAction(self.redo)
        #self.menu_edit.addAction(self.copy)
        #self.menu_edit.addAction(self.crop)
        #self.menu_edit.addAction(self.insert)
        #self.menu_edit.addAction(self.select_all)
        self.menu_edit.addSeparator()
        self.menu_edit.addAction(self.undo_query)
        self.menu_edit.addAction(self.redo_query)
        self.menu_edit.addAction(self.query_list)
        #self.menu_edit.addSeparator()
        #self.menu_edit.addAction(self.save_result)
        #self.menu_edit.addAction(self.undo_all)
        #self.menu_edit.addSeparator()
        #self.menu_edit.addAction(self.preferences)
        self.menu_search.addAction(self.searchFulltext)
        #self.menu_search.addAction(self.search_all)
        self.menu_search.addAction(self.searchCompl)
        self.menu_search.addAction(self.searchKw)
        self.menu_search.addAction(self.searchDupl)
        #self.menu_help.addAction(self.help)
        self.menu_help.addAction(self.about)

        #self.menu_help.addAction(self.report_error)

        self.menu_help.addSeparator()
        self.menu_help.addAction(self.database_info)
        self.menu.addAction(self.action_home)
        self.menu.addAction(self.action_7)
        self.menu.addAction(self.action_8)
        #self.menu.addAction(self.action_9)
        #self.menu.addAction(self.action_10)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_edit.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_search.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())
        self.toolBar.addAction(self.toolBarOpenDatabase)
        self.toolBar.addAction(self.toolBarCloseDatabase)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.toolBarHome)
        self.toolBar.addAction(self.toolBarPrev)
        self.toolBar.addAction(self.toolBarNext)
        self.toolBar.addAction(self.toolBarEnd)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.toolBarNewEntry)
        self.toolBar.addAction(self.toolBarEditEntry)
        self.toolBar.addAction(self.toolBarDeleteEntry)
        self.toolBar.addAction(self.toolBarUndo)
        self.toolBar.addAction(self.toolBarCommit)
        self.toolBar.addAction(self.toolBarReset)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #dateEdit_publ_date                                                                                                                                                                                   
        #lineEdit_year                                                                                                                                                                                         



    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.clear()
        self.tableWidget.setColumnCount(18)
        self.tableWidget.setRowCount(3)
        headerItem = QtGui.QTableWidgetItem()
        headerItem.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setVerticalHeaderItem(0,headerItem)
        headerItem1 = QtGui.QTableWidgetItem()
        headerItem1.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setVerticalHeaderItem(1,headerItem1)
        headerItem2 = QtGui.QTableWidgetItem()
        headerItem2.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setVerticalHeaderItem(2,headerItem2)
        headerItem3 = QtGui.QTableWidgetItem()
        headerItem3.setText(QtGui.QApplication.translate("MainWindow", "pdf", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setHorizontalHeaderItem(0,headerItem3)
        headerItem4 = QtGui.QTableWidgetItem()
        headerItem4.setText(QtGui.QApplication.translate("MainWindow", "Автор(ы)", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setHorizontalHeaderItem(1,headerItem4)
        headerItem5 = QtGui.QTableWidgetItem()
        headerItem5.setText(QtGui.QApplication.translate("MainWindow", "Год", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setHorizontalHeaderItem(2,headerItem5)
        headerItem6 = QtGui.QTableWidgetItem()
        headerItem6.setText(QtGui.QApplication.translate("MainWindow", "Название (ориг.)", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setHorizontalHeaderItem(3,headerItem6)
        headerItem7 = QtGui.QTableWidgetItem()
        headerItem7.setText(QtGui.QApplication.translate("MainWindow", "Название (альтерн.)", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setHorizontalHeaderItem(4,headerItem7)
        headerItem8 = QtGui.QTableWidgetItem()
        headerItem8.setText(QtGui.QApplication.translate("MainWindow", "Источник", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setHorizontalHeaderItem(5,headerItem8)
        headerItem9 = QtGui.QTableWidgetItem()
        headerItem9.setText(QtGui.QApplication.translate("MainWindow", "Тип публикации", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setHorizontalHeaderItem(6,headerItem9)
        headerItem10 = QtGui.QTableWidgetItem()
        headerItem10.setText(QtGui.QApplication.translate("MainWindow", "Ключевые слова", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setHorizontalHeaderItem(7,headerItem10)
        headerItem11 = QtGui.QTableWidgetItem()
        headerItem11.setText(QtGui.QApplication.translate("MainWindow", "Абстракт", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setHorizontalHeaderItem(8,headerItem11)
        headerItem12 = QtGui.QTableWidgetItem()
        headerItem12.setText(QtGui.QApplication.translate("MainWindow", "Номер патента", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setHorizontalHeaderItem(9,headerItem12)
        headerItem13 = QtGui.QTableWidgetItem()
        headerItem13.setText(QtGui.QApplication.translate("MainWindow", "Том", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setHorizontalHeaderItem(10,headerItem13)
        headerItem14 = QtGui.QTableWidgetItem()
        headerItem14.setText(QtGui.QApplication.translate("MainWindow", "Номер", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setHorizontalHeaderItem(11,headerItem14)
        headerItem15 = QtGui.QTableWidgetItem()
        headerItem15.setText(QtGui.QApplication.translate("MainWindow", "Страницы", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setHorizontalHeaderItem(12,headerItem15)
        headerItem16 = QtGui.QTableWidgetItem()
        headerItem16.setText(QtGui.QApplication.translate("MainWindow", "Место издания", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setHorizontalHeaderItem(13,headerItem16)
        headerItem17 = QtGui.QTableWidgetItem()
        headerItem17.setText(QtGui.QApplication.translate("MainWindow", "Издательство", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setHorizontalHeaderItem(14,headerItem17)
        headerItem18 = QtGui.QTableWidgetItem()
        headerItem18.setText(QtGui.QApplication.translate("MainWindow", "Язык публикации", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setHorizontalHeaderItem(15,headerItem18)
        headerItem19 = QtGui.QTableWidgetItem()
        headerItem19.setText(QtGui.QApplication.translate("MainWindow", "Время добавления в базу", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setHorizontalHeaderItem(16,headerItem19)
        headerItem20 = QtGui.QTableWidgetItem()
        headerItem20.setText(QtGui.QApplication.translate("MainWindow", "Путь до полнотекстовой публикации", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setHorizontalHeaderItem(17,headerItem20)
        self.menu_file.setTitle(QtGui.QApplication.translate("MainWindow", "&Файл", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_edit.setTitle(QtGui.QApplication.translate("MainWindow", "&Правка", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_search.setTitle(QtGui.QApplication.translate("MainWindow", "&Поиск", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_help.setTitle(QtGui.QApplication.translate("MainWindow", "&Помощь", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setTitle(QtGui.QApplication.translate("MainWindow", "&Вид", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", u"Панель инструментов", None, QtGui.QApplication.UnicodeUTF8))
        self.textBrowser.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Авторы", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("MainWindow", "Оригинальное название", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("MainWindow", "Альтернативное название", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Год", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("MainWindow", "Источник", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("MainWindow", "Издательство", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Место издания", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("MainWindow", "Редакторы", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Том", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Номер", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("MainWindow", "Выпуск", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Серия", None, QtGui.QApplication.UnicodeUTF8))
        self.label_48.setText(QtGui.QApplication.translate("MainWindow", "Часть", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("MainWindow", "Страницы", None, QtGui.QApplication.UnicodeUTF8))
        self.label_51.setText(QtGui.QApplication.translate("MainWindow", "Таблицы", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Карты", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Иллюстрации", None, QtGui.QApplication.UnicodeUTF8))
        self.label_54.setText(QtGui.QApplication.translate("MainWindow", "Количество публикаций", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("MainWindow", "Zool. Record", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("MainWindow", "Область серии", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("MainWindow", "Язык публикации", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Страна публикации", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Тип публикации", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Номер редакции МПК", None, QtGui.QApplication.UnicodeUTF8))
        self.label_53.setText(QtGui.QApplication.translate("MainWindow", "Основной индекс МПК", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Имя патентообладателя", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("MainWindow", "Номер публикации", None, QtGui.QApplication.UnicodeUTF8))
        self.label_49.setText(QtGui.QApplication.translate("MainWindow", "Дата публикации", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Код ссылки", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "УДК", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "ISSN", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Файл с публикацией", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Общие ключевые слова", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Таксономические ключевые слова", None, QtGui.QApplication.UnicodeUTF8))
        self.label_52.setText(QtGui.QApplication.translate("MainWindow", "Реферат", None, QtGui.QApplication.UnicodeUTF8))
        self.create.setText(QtGui.QApplication.translate("MainWindow", "&Создать", None, QtGui.QApplication.UnicodeUTF8))
        self.create.setEnabled(False)
        self.create.setToolTip(QtGui.QApplication.translate("MainWindow", "Создать базу данных", None, QtGui.QApplication.UnicodeUTF8))
        self.create.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.open_.setText(QtGui.QApplication.translate("MainWindow", "&Открыть", None, QtGui.QApplication.UnicodeUTF8))
        self.open_.setToolTip(QtGui.QApplication.translate("MainWindow", "Открыть базу данных", None, QtGui.QApplication.UnicodeUTF8))
        self.open_.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.open_.setEnabled(False)
        self.close.setText(QtGui.QApplication.translate("MainWindow", "&Закрыть", None, QtGui.QApplication.UnicodeUTF8))
        self.close.setToolTip(QtGui.QApplication.translate("MainWindow", "Закрыть базу данных", None, QtGui.QApplication.UnicodeUTF8))
        self.close.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+C", None, QtGui.QApplication.UnicodeUTF8))
        self.close.setEnabled(False)
        self.save.setText(QtGui.QApplication.translate("MainWindow", "&Сохранить", None, QtGui.QApplication.UnicodeUTF8))
        self.save.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        #self.save.setEnabled(False)
        self.save_as.setText(QtGui.QApplication.translate("MainWindow", "&Сохранить как", None, QtGui.QApplication.UnicodeUTF8))
        self.save_as.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+S", None, QtGui.QApplication.UnicodeUTF8))
        self.save_as.setEnabled(False)
        self.del_.setText(QtGui.QApplication.translate("MainWindow", "&Удалить", None, QtGui.QApplication.UnicodeUTF8))
        self.del_.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+D", None, QtGui.QApplication.UnicodeUTF8))
        self.dumpall.setText(QtGui.QApplication.translate("MainWindow", "&Сохранить дамп базы", None, QtGui.QApplication.UnicodeUTF8))
        self.write_in.setText(QtGui.QApplication.translate("MainWindow", "&Экспотировать", None, QtGui.QApplication.UnicodeUTF8))
        self.write_in.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+W", None, QtGui.QApplication.UnicodeUTF8))
        self.concatenate.setText(QtGui.QApplication.translate("MainWindow", "&Объединить", None, QtGui.QApplication.UnicodeUTF8))
        self.concatenate.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+J", None, QtGui.QApplication.UnicodeUTF8))
        self.concatenate.setEnabled(False)
        self.write_from.setText(QtGui.QApplication.translate("MainWindow", "&Импортировать", None, QtGui.QApplication.UnicodeUTF8))
        self.write_from.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+E", None, QtGui.QApplication.UnicodeUTF8))
        self.sort_.setText(QtGui.QApplication.translate("MainWindow", "&Сортировать", None, QtGui.QApplication.UnicodeUTF8))
        self.sort_.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+S", None, QtGui.QApplication.UnicodeUTF8))
        self.sort_.setEnabled(False)
        self.print_.setText(QtGui.QApplication.translate("MainWindow", "&Печать", None, QtGui.QApplication.UnicodeUTF8))
        self.print_.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        
        self.exit_.setText(QtGui.QApplication.translate("MainWindow", "&Выход", None, QtGui.QApplication.UnicodeUTF8))
        self.exit_.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.undo.setText(QtGui.QApplication.translate("MainWindow", "&Отменить", None, QtGui.QApplication.UnicodeUTF8))
        self.undo.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Z", None, QtGui.QApplication.UnicodeUTF8))
        
        self.undo_query.setText(QtGui.QApplication.translate("MainWindow", "&Предыдущий запрос", None, QtGui.QApplication.UnicodeUTF8))
        self.redo_query.setText(QtGui.QApplication.translate("MainWindow", "&Следующий запрос", None, QtGui.QApplication.UnicodeUTF8))
        self.query_list.setText(QtGui.QApplication.translate("MainWindow", "&Список запросов", None, QtGui.QApplication.UnicodeUTF8))
        self.save_result.setText(QtGui.QApplication.translate("MainWindow", "&Сохранить результаты поиска", None, QtGui.QApplication.UnicodeUTF8))

        self.redo.setText(QtGui.QApplication.translate("MainWindow", "&Повторить", None, QtGui.QApplication.UnicodeUTF8))
        self.redo.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Y", None, QtGui.QApplication.UnicodeUTF8))
        self.copy.setText(QtGui.QApplication.translate("MainWindow", "&Копировать", None, QtGui.QApplication.UnicodeUTF8))
        self.copy.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.crop.setText(QtGui.QApplication.translate("MainWindow", "&Вырезать", None, QtGui.QApplication.UnicodeUTF8))
        self.crop.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+X", None, QtGui.QApplication.UnicodeUTF8))
        self.insert.setText(QtGui.QApplication.translate("MainWindow", "&Вставить", None, QtGui.QApplication.UnicodeUTF8))
        self.insert.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+V", None, QtGui.QApplication.UnicodeUTF8))
        self.select_all.setText(QtGui.QApplication.translate("MainWindow", "&Выделить всё", None, QtGui.QApplication.UnicodeUTF8))
        self.select_all.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+A", None, QtGui.QApplication.UnicodeUTF8))
        self.undo_all.setText(QtGui.QApplication.translate("MainWindow", "&Отменить всё", None, QtGui.QApplication.UnicodeUTF8))
        self.undo_all.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+Z", None, QtGui.QApplication.UnicodeUTF8))
        #self.search_all.setText(QtGui.QApplication.translate("MainWindow", "&Поиск по всем полям базы данных", None, QtGui.QApplication.UnicodeUTF8))
        #self.search_all.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+A", None, QtGui.QApplication.UnicodeUTF8))
        self.searchCompl.setText(QtGui.QApplication.translate("MainWindow", "&Поиск по сложному запросу", None, QtGui.QApplication.UnicodeUTF8))
        self.searchCompl.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+C", None, QtGui.QApplication.UnicodeUTF8))
        self.searchKw.setText(QtGui.QApplication.translate("MainWindow", "&Поиск по ключевым словам", None, QtGui.QApplication.UnicodeUTF8))
        self.searchKw.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+K", None, QtGui.QApplication.UnicodeUTF8))
        #self.searchTaxKw.setText(QtGui.QApplication.translate("MainWindow", "&Поиск по совокупности таксономических ключевых слов", None, QtGui.QApplication.UnicodeUTF8))
        #self.searchTaxKw.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+T", None, QtGui.QApplication.UnicodeUTF8))
        self.help.setText(QtGui.QApplication.translate("MainWindow", "&Справка", None, QtGui.QApplication.UnicodeUTF8))
        self.help.setEnabled(False)
        self.help.setShortcut(QtGui.QApplication.translate("MainWindow", "F1", None, QtGui.QApplication.UnicodeUTF8))
        self.about.setText(QtGui.QApplication.translate("MainWindow", "&О программе", None, QtGui.QApplication.UnicodeUTF8))
        self.report_error.setText(QtGui.QApplication.translate("MainWindow", "&Сообщить об ошибке", None, QtGui.QApplication.UnicodeUTF8))
        self.report_error.setEnabled(False)
        self.database_info.setText(QtGui.QApplication.translate("MainWindow", "&Информация о базе данных", None, QtGui.QApplication.UnicodeUTF8))
        self.database_info.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+I", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarHome.setText(QtGui.QApplication.translate("MainWindow", "в начало", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarHome.setToolTip(QtGui.QApplication.translate("MainWindow", "Показать все записи", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarHome.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+<", None, QtGui.QApplication.UnicodeUTF8))
        #self.toolBarPrev.setText(QtGui.QApplication.translate("MainWindow", "назад", None, QtGui.QApplication.UnicodeUTF8))
        #self.toolBarPrev.setToolTip(QtGui.QApplication.translate("MainWindow", "Переход к предыдущей записи", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarPrev.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+B", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarNext.setText(QtGui.QApplication.translate("MainWindow", "вперед", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarNext.setToolTip(QtGui.QApplication.translate("MainWindow", "Переход к следующей записи", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarNext.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarEnd.setText(QtGui.QApplication.translate("MainWindow", "в конец", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarEnd.setToolTip(QtGui.QApplication.translate("MainWindow", "Переход к последней записи", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarEnd.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+>", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarOpenDatabase.setText(QtGui.QApplication.translate("MainWindow", "открыть", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarOpenDatabase.setToolTip(QtGui.QApplication.translate("MainWindow", "Выбрать базу данных", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarCloseDatabase.setText(QtGui.QApplication.translate("MainWindow", "закрыть", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarCloseDatabase.setToolTip(QtGui.QApplication.translate("MainWindow", "Закрыть базу данных", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarNewEntry.setText(QtGui.QApplication.translate("MainWindow", "добавить", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarNewEntry.setToolTip(QtGui.QApplication.translate("MainWindow", "Добавить новую запись", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarNewEntry.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Alt+A", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarDeleteEntry.setText(QtGui.QApplication.translate("MainWindow", "удалить", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarDeleteEntry.setToolTip(QtGui.QApplication.translate("MainWindow", "Удалить текущую запись", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarEditEntry.setText(QtGui.QApplication.translate("MainWindow", "править", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarEditEntry.setToolTip(QtGui.QApplication.translate("MainWindow", "редактировать текущую запись", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarSimpleSearch.setText(QtGui.QApplication.translate("MainWindow", "поиск", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarSimpleSearch.setToolTip(QtGui.QApplication.translate("MainWindow", "Поиск по базе данных", None, QtGui.QApplication.UnicodeUTF8))
        self.preferences.setText(QtGui.QApplication.translate("MainWindow", "&Настройки", None, QtGui.QApplication.UnicodeUTF8))
        self.preferences.setToolTip(QtGui.QApplication.translate("MainWindow", "Настройка поведения, внешнего вида и других параметров", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarUndo.setText(QtGui.QApplication.translate("MainWindow", "отменить", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarUndo.setToolTip(QtGui.QApplication.translate("MainWindow", "Отмена последнего действия", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarReset.setText(QtGui.QApplication.translate("MainWindow", "сброс", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarReset.setToolTip(QtGui.QApplication.translate("MainWindow", "Сброс соединения при ошибке в запросе", None, QtGui.QApplication.UnicodeUTF8))
        self.searchFulltext.setText(QtGui.QApplication.translate("MainWindow", "&Полнотекстовый поиск", None, QtGui.QApplication.UnicodeUTF8))
        self.searchFulltext.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+F", None, QtGui.QApplication.UnicodeUTF8))
        self.searchDupl.setText(QtGui.QApplication.translate("MainWindow", "&Поиск дублей", None, QtGui.QApplication.UnicodeUTF8))
        self.searchDupl.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+D", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarCommit.setText(QtGui.QApplication.translate("MainWindow", "сохранить", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarCommit.setToolTip(QtGui.QApplication.translate("MainWindow", "Сохранить изменения", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarCommit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Alt+S", None, QtGui.QApplication.UnicodeUTF8))
        self.action_dfg.setText(QtGui.QApplication.translate("MainWindow", "&dfg", None, QtGui.QApplication.UnicodeUTF8))
        self.action_asd.setText(QtGui.QApplication.translate("MainWindow", "& asd", None, QtGui.QApplication.UnicodeUTF8))
        self.action_sdf.setText(QtGui.QApplication.translate("MainWindow", "&sdf", None, QtGui.QApplication.UnicodeUTF8))
        self.action_sdf_2.setText(QtGui.QApplication.translate("MainWindow", "&sdf", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDfg.setText(QtGui.QApplication.translate("MainWindow", "dfg", None, QtGui.QApplication.UnicodeUTF8))
        self.action_dfgh.setText(QtGui.QApplication.translate("MainWindow", "&dfgh", None, QtGui.QApplication.UnicodeUTF8))
        self.action_hgf.setText(QtGui.QApplication.translate("MainWindow", "&hgf", None, QtGui.QApplication.UnicodeUTF8))
        self.action_aaa.setText(QtGui.QApplication.translate("MainWindow", "&aaa", None, QtGui.QApplication.UnicodeUTF8))
        self.actionJapan.setText(QtGui.QApplication.translate("MainWindow", "japan", None, QtGui.QApplication.UnicodeUTF8))
        self.action_home.setText(QtGui.QApplication.translate("MainWindow", "&В начало", None, QtGui.QApplication.UnicodeUTF8))
        self.action_7.setText(QtGui.QApplication.translate("MainWindow", "&Краткий", None, QtGui.QApplication.UnicodeUTF8))
        
        self.action_8.setText(QtGui.QApplication.translate("MainWindow", "&Все поля", None, QtGui.QApplication.UnicodeUTF8))
        self.action_9.setText(QtGui.QApplication.translate("MainWindow", "&Результаты поиска", None, QtGui.QApplication.UnicodeUTF8))
        self.action_10.setText(QtGui.QApplication.translate("MainWindow", "&Форматированные ссылки", None, QtGui.QApplication.UnicodeUTF8))

        
        
