# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dupl_delete.ui'
#
# Created: Sun Apr 22 18:18:13 2012
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_duplDeleteDialog(object):
    def setupUi(self, duplDeleteDialog):
        duplDeleteDialog.setObjectName("duplDeleteDialog")
        duplDeleteDialog.resize(480, 286)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(duplDeleteDialog.sizePolicy().hasHeightForWidth())
        duplDeleteDialog.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(duplDeleteDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.entryNumber = QtGui.QLabel(duplDeleteDialog)
        self.entryNumber.setObjectName("entryNumber")
        self.gridLayout.addWidget(self.entryNumber, 0, 0, 1, 1)
        self.entryLabel = QtGui.QTextBrowser(duplDeleteDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entryLabel.sizePolicy().hasHeightForWidth())
        self.entryLabel.setSizePolicy(sizePolicy)
        self.entryLabel.setMinimumSize(QtCore.QSize(0, 27))
        self.entryLabel.setObjectName("entryLabel")
        self.gridLayout.addWidget(self.entryLabel, 1, 0, 1, 4)
        self.foundNumber = QtGui.QLabel(duplDeleteDialog)
        self.foundNumber.setObjectName("foundNumber")
        self.gridLayout.addWidget(self.foundNumber, 2, 0, 1, 1)
        self.frame = QtGui.QFrame(duplDeleteDialog)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setLineWidth(1)
        self.frame.setMidLineWidth(0)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox = QtGui.QCheckBox(self.frame)
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.dupl1Label = QtGui.QTextBrowser(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dupl1Label.sizePolicy().hasHeightForWidth())
        self.dupl1Label.setSizePolicy(sizePolicy)
        self.dupl1Label.setMinimumSize(QtCore.QSize(0, 27))
        self.dupl1Label.setObjectName("dupl1Label")
        self.horizontalLayout.addWidget(self.dupl1Label)
        self.gridLayout.addWidget(self.frame, 4, 0, 1, 4)
        self.frame_2 = QtGui.QFrame(duplDeleteDialog)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_2 = QtGui.QCheckBox(self.frame_2)
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_2.addWidget(self.checkBox_2)
        self.dupl2Label = QtGui.QTextBrowser(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dupl2Label.sizePolicy().hasHeightForWidth())
        self.dupl2Label.setSizePolicy(sizePolicy)
        self.dupl2Label.setMinimumSize(QtCore.QSize(0, 27))
        self.dupl2Label.setObjectName("dupl2Label")
        self.horizontalLayout_2.addWidget(self.dupl2Label)
        self.gridLayout.addWidget(self.frame_2, 5, 0, 1, 4)
        self.frame_3 = QtGui.QFrame(duplDeleteDialog)
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_3 = QtGui.QCheckBox(self.frame_3)
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_3.addWidget(self.checkBox_3)
        self.dupl3Label = QtGui.QTextBrowser(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dupl3Label.sizePolicy().hasHeightForWidth())
        self.dupl3Label.setSizePolicy(sizePolicy)
        self.dupl3Label.setMinimumSize(QtCore.QSize(0, 27))
        self.dupl3Label.setObjectName("dupl3Label")
        self.horizontalLayout_3.addWidget(self.dupl3Label)
        self.gridLayout.addWidget(self.frame_3, 6, 0, 1, 4)
        self.remainNumber = QtGui.QLabel(duplDeleteDialog)
        self.remainNumber.setObjectName("remainNumber")
        self.gridLayout.addWidget(self.remainNumber, 0, 2, 1, 1)
        self.nextButton = QtGui.QPushButton(duplDeleteDialog)
        self.nextButton.setObjectName("nextButton")
        self.gridLayout.addWidget(self.nextButton, 7, 3, 1, 1)
        self.delButton = QtGui.QPushButton(duplDeleteDialog)
        self.delButton.setObjectName("delButton")
        self.gridLayout.addWidget(self.delButton, 7, 2, 1, 1)
        self.backButton = QtGui.QPushButton(duplDeleteDialog)
        self.backButton.setObjectName("backButton")
        self.gridLayout.addWidget(self.backButton, 7, 1, 1, 1)

        self.retranslateUi(duplDeleteDialog)
        QtCore.QMetaObject.connectSlotsByName(duplDeleteDialog)

    def retranslateUi(self, duplDeleteDialog):
        duplDeleteDialog.setWindowTitle(QtGui.QApplication.translate("duplDeleteDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.entryNumber.setText(QtGui.QApplication.translate("duplDeleteDialog", "Для записи № 123", None, QtGui.QApplication.UnicodeUTF8))
        self.foundNumber.setText(QtGui.QApplication.translate("duplDeleteDialog", "найдено:", None, QtGui.QApplication.UnicodeUTF8))
        self.remainNumber.setText(QtGui.QApplication.translate("duplDeleteDialog", "Осталось 123 необработанных", None, QtGui.QApplication.UnicodeUTF8))
        self.nextButton.setText(QtGui.QApplication.translate("duplDeleteDialog", "Дальше", None, QtGui.QApplication.UnicodeUTF8))
        self.delButton.setText(QtGui.QApplication.translate("duplDeleteDialog", "Удалить", None, QtGui.QApplication.UnicodeUTF8))
        self.backButton.setText(QtGui.QApplication.translate("duplDeleteDialog", "Обратно", None, QtGui.QApplication.UnicodeUTF8))

