
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search_form.ui'
#
# Created: Mon May  3 21:26:39 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_searchallForm(object):
    def setupUi(self, searchallForm):
        searchallForm.setObjectName("searchallForm")
        searchallForm.resize(1220, 411)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(searchallForm.sizePolicy().hasHeightForWidth())
        searchallForm.setSizePolicy(sizePolicy)
        self.verticalLayout = QtGui.QVBoxLayout(searchallForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupFields = QtGui.QGroupBox(searchallForm)
        self.groupFields.setObjectName("groupFields")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupFields)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.field_comboBox0 = QtGui.QComboBox(self.groupFields)
        self.field_comboBox0.setObjectName("field_comboBox0")
        self.field_comboBox0.addItem("")
        self.field_comboBox0.addItem("")
        self.field_comboBox0.addItem("")
        self.field_comboBox0.addItem("")
        self.field_comboBox0.addItem("")
        self.field_comboBox0.addItem("")
        self.field_comboBox0.addItem("")
        self.field_comboBox0.addItem("")
        self.field_comboBox0.addItem("")
        self.field_comboBox0.addItem("")
        self.field_comboBox0.addItem("")
        self.field_comboBox0.addItem("")
        self.field_comboBox0.addItem("")
        self.field_comboBox0.addItem("")
        self.field_comboBox0.addItem("")
        self.field_comboBox0.addItem("")
        self.field_comboBox0.addItem("")
        self.field_comboBox0.addItem("")
        self.field_comboBox0.addItem("")
        self.field_comboBox0.addItem("")
        self.field_comboBox0.addItem("")
        self.field_comboBox0.addItem("")
        self.field_comboBox0.addItem("")
        self.field_comboBox0.addItem("")
        self.field_comboBox0.addItem("")
        self.field_comboBox0.addItem("")
        self.field_comboBox0.addItem("")
        self.field_comboBox0.addItem("")
        self.field_comboBox0.addItem("")
        self.field_comboBox0.addItem("")
        self.field_comboBox0.addItem("")
        self.field_comboBox0.addItem("")
        self.field_comboBox0.addItem("")
        self.field_comboBox0.addItem("")
        self.field_comboBox0.addItem("")
        self.field_comboBox0.addItem("")
        self.field_comboBox0.addItem("")
        self.gridLayout_2.addWidget(self.field_comboBox0, 0, 1, 1, 1)
        self.cont_comboBox0 = QtGui.QComboBox(self.groupFields)
        self.cont_comboBox0.setObjectName("cont_comboBox0")
        self.cont_comboBox0.addItem("")
        self.cont_comboBox0.addItem("")
        self.cont_comboBox0.addItem("")
        self.cont_comboBox0.addItem("")
        self.cont_comboBox0.addItem("")
        self.cont_comboBox0.addItem("")
        self.cont_comboBox0.addItem("")
        self.cont_comboBox0.addItem("")
        self.cont_comboBox0.addItem("")
        self.cont_comboBox0.addItem("")
        self.cont_comboBox0.addItem("")
        self.gridLayout_2.addWidget(self.cont_comboBox0, 0, 2, 1, 1)
        self.search_lineEdit = QtGui.QLineEdit(self.groupFields)
        self.search_lineEdit.setObjectName("search_lineEdit")
        self.gridLayout_2.addWidget(self.search_lineEdit, 0, 3, 1, 1)
        self.add_button0 = QtGui.QPushButton(self.groupFields)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(25)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_button0.sizePolicy().hasHeightForWidth())
        self.add_button0.setSizePolicy(sizePolicy)
        self.add_button0.setMaximumSize(QtCore.QSize(30, 16777215))
        self.add_button0.setObjectName("add_button0")
        self.gridLayout_2.addWidget(self.add_button0, 0, 5, 1, 1)
        self.add_button2 = QtGui.QPushButton(self.groupFields)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(25)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_button2.sizePolicy().hasHeightForWidth())
        self.add_button2.setSizePolicy(sizePolicy)
        self.add_button2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.add_button2.setObjectName("add_button2")
        self.gridLayout_2.addWidget(self.add_button2, 2, 5, 1, 1)
        self.rem_button2 = QtGui.QPushButton(self.groupFields)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rem_button2.sizePolicy().hasHeightForWidth())
        self.rem_button2.setSizePolicy(sizePolicy)
        self.rem_button2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.rem_button2.setObjectName("rem_button2")
        self.gridLayout_2.addWidget(self.rem_button2, 2, 4, 1, 1)
        self.add_button1 = QtGui.QPushButton(self.groupFields)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(25)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_button1.sizePolicy().hasHeightForWidth())
        self.add_button1.setSizePolicy(sizePolicy)
        self.add_button1.setMaximumSize(QtCore.QSize(30, 16777215))
        self.add_button1.setObjectName("add_button1")
        self.gridLayout_2.addWidget(self.add_button1, 1, 5, 1, 1)
        self.rem_button1 = QtGui.QPushButton(self.groupFields)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rem_button1.sizePolicy().hasHeightForWidth())
        self.rem_button1.setSizePolicy(sizePolicy)
        self.rem_button1.setMaximumSize(QtCore.QSize(30, 16777215))
        self.rem_button1.setObjectName("rem_button1")
        self.gridLayout_2.addWidget(self.rem_button1, 1, 4, 1, 1)
        self.search_lineEdit2 = QtGui.QLineEdit(self.groupFields)
        self.search_lineEdit2.setObjectName("search_lineEdit2")
        self.gridLayout_2.addWidget(self.search_lineEdit2, 2, 3, 1, 1)
        self.search_lineEdit1 = QtGui.QLineEdit(self.groupFields)
        self.search_lineEdit1.setObjectName("search_lineEdit1")
        self.gridLayout_2.addWidget(self.search_lineEdit1, 1, 3, 1, 1)
        self.cont_comboBox2 = QtGui.QComboBox(self.groupFields)
        self.cont_comboBox2.setObjectName("cont_comboBox2")
        self.cont_comboBox2.addItem("")
        self.cont_comboBox2.addItem("")
        self.cont_comboBox2.addItem("")
        self.cont_comboBox2.addItem("")
        self.cont_comboBox2.addItem("")
        self.cont_comboBox2.addItem("")
        self.cont_comboBox2.addItem("")
        self.cont_comboBox2.addItem("")
        self.cont_comboBox2.addItem("")
        self.cont_comboBox2.addItem("")
        self.cont_comboBox2.addItem("")
        self.gridLayout_2.addWidget(self.cont_comboBox2, 2, 2, 1, 1)
        self.cont_comboBox1 = QtGui.QComboBox(self.groupFields)
        self.cont_comboBox1.setObjectName("cont_comboBox1")
        self.cont_comboBox1.addItem("")
        self.cont_comboBox1.addItem("")
        self.cont_comboBox1.addItem("")
        self.cont_comboBox1.addItem("")
        self.cont_comboBox1.addItem("")
        self.cont_comboBox1.addItem("")
        self.cont_comboBox1.addItem("")
        self.cont_comboBox1.addItem("")
        self.cont_comboBox1.addItem("")
        self.cont_comboBox1.addItem("")
        self.cont_comboBox1.addItem("")
        self.gridLayout_2.addWidget(self.cont_comboBox1, 1, 2, 1, 1)
        self.field_comboBox2 = QtGui.QComboBox(self.groupFields)
        self.field_comboBox2.setObjectName("field_comboBox2")
        self.field_comboBox2.addItem("")
        self.field_comboBox2.addItem("")
        self.field_comboBox2.addItem("")
        self.field_comboBox2.addItem("")
        self.field_comboBox2.addItem("")
        self.field_comboBox2.addItem("")
        self.field_comboBox2.addItem("")
        self.field_comboBox2.addItem("")
        self.field_comboBox2.addItem("")
        self.field_comboBox2.addItem("")
        self.field_comboBox2.addItem("")
        self.field_comboBox2.addItem("")
        self.field_comboBox2.addItem("")
        self.field_comboBox2.addItem("")
        self.field_comboBox2.addItem("")
        self.field_comboBox2.addItem("")
        self.field_comboBox2.addItem("")
        self.field_comboBox2.addItem("")
        self.field_comboBox2.addItem("")
        self.field_comboBox2.addItem("")
        self.field_comboBox2.addItem("")
        self.field_comboBox2.addItem("")
        self.field_comboBox2.addItem("")
        self.field_comboBox2.addItem("")
        self.field_comboBox2.addItem("")
        self.field_comboBox2.addItem("")
        self.field_comboBox2.addItem("")
        self.field_comboBox2.addItem("")
        self.field_comboBox2.addItem("")
        self.field_comboBox2.addItem("")
        self.field_comboBox2.addItem("")
        self.field_comboBox2.addItem("")
        self.field_comboBox2.addItem("")
        self.field_comboBox2.addItem("")
        self.field_comboBox2.addItem("")
        self.field_comboBox2.addItem("")
        self.field_comboBox2.addItem("")
        self.field_comboBox2.addItem("")
        self.gridLayout_2.addWidget(self.field_comboBox2, 2, 1, 1, 1)
        self.field_comboBox1 = QtGui.QComboBox(self.groupFields)
        self.field_comboBox1.setObjectName("field_comboBox1")
        self.field_comboBox1.addItem("")
        self.field_comboBox1.addItem("")
        self.field_comboBox1.addItem("")
        self.field_comboBox1.addItem("")
        self.field_comboBox1.addItem("")
        self.field_comboBox1.addItem("")
        self.field_comboBox1.addItem("")
        self.field_comboBox1.addItem("")
        self.field_comboBox1.addItem("")
        self.field_comboBox1.addItem("")
        self.field_comboBox1.addItem("")
        self.field_comboBox1.addItem("")
        self.field_comboBox1.addItem("")
        self.field_comboBox1.addItem("")
        self.field_comboBox1.addItem("")
        self.field_comboBox1.addItem("")
        self.field_comboBox1.addItem("")
        self.field_comboBox1.addItem("")
        self.field_comboBox1.addItem("")
        self.field_comboBox1.addItem("")
        self.field_comboBox1.addItem("")
        self.field_comboBox1.addItem("")
        self.field_comboBox1.addItem("")
        self.field_comboBox1.addItem("")
        self.field_comboBox1.addItem("")
        self.field_comboBox1.addItem("")
        self.field_comboBox1.addItem("")
        self.field_comboBox1.addItem("")
        self.field_comboBox1.addItem("")
        self.field_comboBox1.addItem("")
        self.field_comboBox1.addItem("")
        self.field_comboBox1.addItem("")
        self.field_comboBox1.addItem("")
        self.field_comboBox1.addItem("")
        self.field_comboBox1.addItem("")
        self.field_comboBox1.addItem("")
        self.field_comboBox1.addItem("")
        self.gridLayout_2.addWidget(self.field_comboBox1, 1, 1, 1, 1)
        self.and_comboBox2 = QtGui.QComboBox(self.groupFields)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.and_comboBox2.sizePolicy().hasHeightForWidth())
        self.and_comboBox2.setSizePolicy(sizePolicy)
        self.and_comboBox2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.and_comboBox2.setObjectName("and_comboBox2")
        self.and_comboBox2.addItem("")
        self.and_comboBox2.addItem("")
        self.and_comboBox2.addItem("")
        self.and_comboBox2.addItem("")
        self.gridLayout_2.addWidget(self.and_comboBox2, 2, 0, 1, 1)
        self.and_comboBox1 = QtGui.QComboBox(self.groupFields)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.and_comboBox1.sizePolicy().hasHeightForWidth())
        self.and_comboBox1.setSizePolicy(sizePolicy)
        self.and_comboBox1.setMaximumSize(QtCore.QSize(40, 16777215))
        self.and_comboBox1.setObjectName("and_comboBox1")
        self.and_comboBox1.addItem("")
        self.and_comboBox1.addItem("")
        self.and_comboBox1.addItem("")
        self.and_comboBox1.addItem("")
        
        self.gridLayout_2.addWidget(self.and_comboBox1, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupFields)
        self.groupParams = QtGui.QGroupBox(searchallForm)
        self.groupParams.setObjectName("groupParams")
        self.gridLayout = QtGui.QGridLayout(self.groupParams)
        self.gridLayout.setObjectName("gridLayout")
        #self.sel_search_comboBox = QtGui.QComboBox(self.groupParams)
        #self.sel_search_comboBox.setObjectName("sel_search_comboBox")
        #self.sel_search_comboBox.addItem("")
        #self.sel_search_comboBox.addItem("")
        #self.sel_search_comboBox.addItem("")
        #self.sel_search_comboBox.addItem("")
        #self.sel_search_comboBox.addItem("")
        #self.gridLayout.addWidget(self.sel_search_comboBox, 0, 0, 1, 1)
        self.checkBox_search_results = QtGui.QCheckBox(self.groupParams)
        self.checkBox_search_results.setObjectName("checkBox_search_results")
        self.search_in_selected = QtGui.QCheckBox(self)
        self.search_in_selected.setObjectName("search_in_selected")
        self.search_in_selected.setText(u'Искать в выделенном')
        self.gridLayout.addWidget(self.search_in_selected, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.checkBox_search_results, 0, 1, 1, 1)
        #self.save_queryButton = QtGui.QPushButton(self.groupParams)
        #self.save_queryButton.setObjectName("save_queryButton")
        #self.gridLayout.addWidget(self.save_queryButton, 2, 0, 1, 1)
        #self.load_queryButton = QtGui.QPushButton(self.groupParams)
        #self.load_queryButton.setObjectName("load_queryButton")
        #self.gridLayout.addWidget(self.load_queryButton, 2, 1, 1, 1)
        self.OKbuttonBox = QtGui.QDialogButtonBox(self.groupParams)
        self.OKbuttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.OKbuttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.OKbuttonBox.setObjectName("OKbuttonBox")
        self.gridLayout.addWidget(self.OKbuttonBox, 3, 4, 1, 1)
        #self.setdef_Button = QtGui.QPushButton(self.groupParams)
        #self.setdef_Button.setObjectName("setdef_Button")
        #self.gridLayout.addWidget(self.setdef_Button, 3, 0, 1, 1)
        #self.rest_defButton = QtGui.QPushButton(self.groupParams)
        #self.rest_defButton.setObjectName("rest_defButton")
        #self.gridLayout.addWidget(self.rest_defButton, 3, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupParams)
        self.connect(self.OKbuttonBox, QtCore.SIGNAL("rejected()"), self.close)
        self.retranslateUi(searchallForm)
        #QtCore.QObject.connect(self.OKbuttonBox, QtCore.SIGNAL("accepted()"), searchallForm.accept)
        #QtCore.QObject.connect(self.OKbuttonBox, QtCore.SIGNAL("rejected()"), searchallForm.reject)
        QtCore.QMetaObject.connectSlotsByName(searchallForm)

    def retranslateUi(self, searchallForm):
        searchallForm.setWindowTitle(QtGui.QApplication.translate("searchallForm", "Настраиваемый поиск", None, QtGui.QApplication.UnicodeUTF8))
        self.groupFields.setTitle(QtGui.QApplication.translate("searchallForm", "Поля", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox0.setItemText(0, QtGui.QApplication.translate("searchallForm", "Авторы", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox0.setItemText(1, QtGui.QApplication.translate("searchallForm", "Название (ориг.)", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox0.setItemText(2, QtGui.QApplication.translate("searchallForm", "Название (альт.)", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox0.setItemText(3, QtGui.QApplication.translate("searchallForm", "Источник", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox0.setItemText(4, QtGui.QApplication.translate("searchallForm", "Редактор", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox0.setItemText(5, QtGui.QApplication.translate("searchallForm", "Место издания", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox0.setItemText(6, QtGui.QApplication.translate("searchallForm", "Издательство", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox0.setItemText(7, QtGui.QApplication.translate("searchallForm", "Год", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox0.setItemText(8, QtGui.QApplication.translate("searchallForm", "Том", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox0.setItemText(9, QtGui.QApplication.translate("searchallForm", "Номер", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox0.setItemText(10, QtGui.QApplication.translate("searchallForm", "Выпуск", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox0.setItemText(11, QtGui.QApplication.translate("searchallForm", "Серия", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox0.setItemText(12, QtGui.QApplication.translate("searchallForm", "Часть", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox0.setItemText(13, QtGui.QApplication.translate("searchallForm", "Страницы", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox0.setItemText(14, QtGui.QApplication.translate("searchallForm", "Таблицы", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox0.setItemText(15, QtGui.QApplication.translate("searchallForm", "Карты", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox0.setItemText(16, QtGui.QApplication.translate("searchallForm", "Иллюстрации", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox0.setItemText(17, QtGui.QApplication.translate("searchallForm", "Ссылки", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox0.setItemText(18, QtGui.QApplication.translate("searchallForm", "Область серии", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox0.setItemText(19, QtGui.QApplication.translate("searchallForm", "Язык", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox0.setItemText(20, QtGui.QApplication.translate("searchallForm", "Дата добавления", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox0.setItemText(21, QtGui.QApplication.translate("searchallForm", "Дата изменения", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox0.setItemText(22, QtGui.QApplication.translate("searchallForm", "Тип публикации", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox0.setItemText(23, QtGui.QApplication.translate("searchallForm", "Реф. код", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox0.setItemText(24, QtGui.QApplication.translate("searchallForm", "УДК", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox0.setItemText(25, QtGui.QApplication.translate("searchallForm", "Zool. Rec.", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox0.setItemText(26, QtGui.QApplication.translate("searchallForm", "ISSN", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox0.setItemText(27, QtGui.QApplication.translate("searchallForm", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox0.setItemText(28, QtGui.QApplication.translate("searchallForm", "Ключевые слова", None, QtGui.QApplication.UnicodeUTF8))
        #self.field_comboBox0.setItemText(27, QtGui.QApplication.translate("searchallForm", "Таксономические ключевые слова", None, QtGui.QApplication.UnicodeUTF8))
        
        self.field_comboBox0.setItemText(29, QtGui.QApplication.translate("searchallForm", "Номер публикации", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox0.setItemText(30, QtGui.QApplication.translate("searchallForm", "Дата публикации", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox0.setItemText(31, QtGui.QApplication.translate("searchallForm", "Страна публикации", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox0.setItemText(32, QtGui.QApplication.translate("searchallForm", "Номер изд. МПК", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox0.setItemText(33, QtGui.QApplication.translate("searchallForm", "Основной инд. МПК", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox0.setItemText(34, QtGui.QApplication.translate("searchallForm", "Владелец патента", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox0.setItemText(35, QtGui.QApplication.translate("searchallForm", "Реферат", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox0.setItemText(36, QtGui.QApplication.translate("searchallForm", "Полный текст", None, QtGui.QApplication.UnicodeUTF8))
        self.cont_comboBox0.setItemText(0, QtGui.QApplication.translate("searchallForm", "содержит", None, QtGui.QApplication.UnicodeUTF8))
        self.cont_comboBox0.setItemText(1, QtGui.QApplication.translate("searchallForm", "не содержит", None, QtGui.QApplication.UnicodeUTF8))
        
        self.cont_comboBox0.setItemText(2, QtGui.QApplication.translate("searchallForm", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.cont_comboBox0.setItemText(3, QtGui.QApplication.translate("searchallForm", "≠", None, QtGui.QApplication.UnicodeUTF8))
        self.cont_comboBox0.setItemText(4, QtGui.QApplication.translate("searchallForm", "≥", None, QtGui.QApplication.UnicodeUTF8))
        self.cont_comboBox0.setItemText(5, QtGui.QApplication.translate("searchallForm", "≤", None, QtGui.QApplication.UnicodeUTF8))
        self.cont_comboBox0.setItemText(6, QtGui.QApplication.translate("searchallForm", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.cont_comboBox0.setItemText(7, QtGui.QApplication.translate("searchallForm", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.cont_comboBox0.setItemText(8, QtGui.QApplication.translate("searchallForm", "начинается с", None, QtGui.QApplication.UnicodeUTF8))
        self.cont_comboBox0.setItemText(9, QtGui.QApplication.translate("searchallForm", "заканчивается на", None, QtGui.QApplication.UnicodeUTF8))
        self.cont_comboBox0.setItemText(10, QtGui.QApplication.translate("searchallForm", "подобен", None, QtGui.QApplication.UnicodeUTF8))
        self.add_button0.setText(QtGui.QApplication.translate("searchallForm", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.add_button2.setText(QtGui.QApplication.translate("searchallForm", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.rem_button2.setText(QtGui.QApplication.translate("searchallForm", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.add_button1.setText(QtGui.QApplication.translate("searchallForm", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.rem_button1.setText(QtGui.QApplication.translate("searchallForm", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.cont_comboBox2.setItemText(0, QtGui.QApplication.translate("searchallForm", "содержит", None, QtGui.QApplication.UnicodeUTF8))
        self.cont_comboBox2.setItemText(1, QtGui.QApplication.translate("searchallForm", "не содержит", None, QtGui.QApplication.UnicodeUTF8))
        self.cont_comboBox2.setItemText(2, QtGui.QApplication.translate("searchallForm", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.cont_comboBox2.setItemText(3, QtGui.QApplication.translate("searchallForm", "≠", None, QtGui.QApplication.UnicodeUTF8))
        self.cont_comboBox2.setItemText(4, QtGui.QApplication.translate("searchallForm", "≥", None, QtGui.QApplication.UnicodeUTF8))
        self.cont_comboBox2.setItemText(5, QtGui.QApplication.translate("searchallForm", "≤", None, QtGui.QApplication.UnicodeUTF8))
        self.cont_comboBox2.setItemText(6, QtGui.QApplication.translate("searchallForm", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.cont_comboBox2.setItemText(7, QtGui.QApplication.translate("searchallForm", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.cont_comboBox2.setItemText(8, QtGui.QApplication.translate("searchallForm", "начинается с", None, QtGui.QApplication.UnicodeUTF8))
        self.cont_comboBox2.setItemText(9, QtGui.QApplication.translate("searchallForm", "заканчивается на", None, QtGui.QApplication.UnicodeUTF8))
        self.cont_comboBox2.setItemText(10, QtGui.QApplication.translate("searchallForm", "подобен", None, QtGui.QApplication.UnicodeUTF8))
        self.cont_comboBox1.setItemText(0, QtGui.QApplication.translate("searchallForm", "содержит", None, QtGui.QApplication.UnicodeUTF8))
        self.cont_comboBox1.setItemText(1, QtGui.QApplication.translate("searchallForm", "не содержит", None, QtGui.QApplication.UnicodeUTF8))
        self.cont_comboBox1.setItemText(2, QtGui.QApplication.translate("searchallForm", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.cont_comboBox1.setItemText(3, QtGui.QApplication.translate("searchallForm", "≠", None, QtGui.QApplication.UnicodeUTF8))
        self.cont_comboBox1.setItemText(4, QtGui.QApplication.translate("searchallForm", "≥", None, QtGui.QApplication.UnicodeUTF8))
        self.cont_comboBox1.setItemText(5, QtGui.QApplication.translate("searchallForm", "≤", None, QtGui.QApplication.UnicodeUTF8))
        self.cont_comboBox1.setItemText(6, QtGui.QApplication.translate("searchallForm", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.cont_comboBox1.setItemText(7, QtGui.QApplication.translate("searchallForm", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.cont_comboBox1.setItemText(8, QtGui.QApplication.translate("searchallForm", "начинается с", None, QtGui.QApplication.UnicodeUTF8))
        self.cont_comboBox1.setItemText(9, QtGui.QApplication.translate("searchallForm", "заканчивается на", None, QtGui.QApplication.UnicodeUTF8))
        self.cont_comboBox1.setItemText(10, QtGui.QApplication.translate("searchallForm", "подобен", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox2.setItemText(0, QtGui.QApplication.translate("searchallForm", "Авторы", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox2.setItemText(1, QtGui.QApplication.translate("searchallForm", "Название (ориг.)", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox2.setItemText(2, QtGui.QApplication.translate("searchallForm", "Название (альт.)", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox2.setItemText(3, QtGui.QApplication.translate("searchallForm", "Источник", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox2.setItemText(4, QtGui.QApplication.translate("searchallForm", "Редактор", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox2.setItemText(5, QtGui.QApplication.translate("searchallForm", "Место издания", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox2.setItemText(6, QtGui.QApplication.translate("searchallForm", "Издательство", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox2.setItemText(7, QtGui.QApplication.translate("searchallForm", "Год", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox2.setItemText(8, QtGui.QApplication.translate("searchallForm", "Том", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox2.setItemText(9, QtGui.QApplication.translate("searchallForm", "Номер", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox2.setItemText(10, QtGui.QApplication.translate("searchallForm", "Выпуск", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox2.setItemText(11, QtGui.QApplication.translate("searchallForm", "Серия", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox2.setItemText(12, QtGui.QApplication.translate("searchallForm", "Часть", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox2.setItemText(13, QtGui.QApplication.translate("searchallForm", "Страницы", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox2.setItemText(14, QtGui.QApplication.translate("searchallForm", "Таблицы", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox2.setItemText(15, QtGui.QApplication.translate("searchallForm", "Карты", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox2.setItemText(16, QtGui.QApplication.translate("searchallForm", "Иллюстрации", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox2.setItemText(17, QtGui.QApplication.translate("searchallForm", "Ссылки", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox2.setItemText(18, QtGui.QApplication.translate("searchallForm", "Область серии", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox2.setItemText(19, QtGui.QApplication.translate("searchallForm", "Язык", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox2.setItemText(20, QtGui.QApplication.translate("searchallForm", "Дата добавления", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox2.setItemText(21, QtGui.QApplication.translate("searchallForm", "Дата изменения", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox2.setItemText(22, QtGui.QApplication.translate("searchallForm", "Тип публикации", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox2.setItemText(23, QtGui.QApplication.translate("searchallForm", "Реф. код", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox2.setItemText(24, QtGui.QApplication.translate("searchallForm", "УДК", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox2.setItemText(25, QtGui.QApplication.translate("searchallForm", "Zool. Rec.", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox2.setItemText(26, QtGui.QApplication.translate("searchallForm", "ISSN", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox2.setItemText(27, QtGui.QApplication.translate("searchallForm", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox2.setItemText(28, QtGui.QApplication.translate("searchallForm", "Ключевые слова", None, QtGui.QApplication.UnicodeUTF8))
        #self.field_comboBox2.setItemText(27, QtGui.QApplication.translate("searchallForm", "Таксономические ключевые слова", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox2.setItemText(29, QtGui.QApplication.translate("searchallForm", "Номер публикации", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox2.setItemText(30, QtGui.QApplication.translate("searchallForm", "Дата публикации", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox2.setItemText(31, QtGui.QApplication.translate("searchallForm", "Страна публикации", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox2.setItemText(32, QtGui.QApplication.translate("searchallForm", "Номер изд. МПК", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox2.setItemText(33, QtGui.QApplication.translate("searchallForm", "Основной инд. МПК", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox2.setItemText(34, QtGui.QApplication.translate("searchallForm", "Владелец патента", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox2.setItemText(35, QtGui.QApplication.translate("searchallForm", "Реферат", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox2.setItemText(36, QtGui.QApplication.translate("searchallForm", "Полный текст", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox1.setItemText(0, QtGui.QApplication.translate("searchallForm", "Авторы", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox1.setItemText(1, QtGui.QApplication.translate("searchallForm", "Название (ориг.)", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox1.setItemText(2, QtGui.QApplication.translate("searchallForm", "Название (альт.)", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox1.setItemText(3, QtGui.QApplication.translate("searchallForm", "Источник", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox1.setItemText(4, QtGui.QApplication.translate("searchallForm", "Редактор", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox1.setItemText(5, QtGui.QApplication.translate("searchallForm", "Место издания", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox1.setItemText(6, QtGui.QApplication.translate("searchallForm", "Издательство", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox1.setItemText(7, QtGui.QApplication.translate("searchallForm", "Год", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox1.setItemText(8, QtGui.QApplication.translate("searchallForm", "Том", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox1.setItemText(9, QtGui.QApplication.translate("searchallForm", "Номер", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox1.setItemText(10, QtGui.QApplication.translate("searchallForm", "Выпуск", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox1.setItemText(11, QtGui.QApplication.translate("searchallForm", "Серия", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox1.setItemText(12, QtGui.QApplication.translate("searchallForm", "Часть", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox1.setItemText(13, QtGui.QApplication.translate("searchallForm", "Страницы", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox1.setItemText(14, QtGui.QApplication.translate("searchallForm", "Таблицы", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox1.setItemText(15, QtGui.QApplication.translate("searchallForm", "Карты", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox1.setItemText(16, QtGui.QApplication.translate("searchallForm", "Иллюстрации", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox1.setItemText(17, QtGui.QApplication.translate("searchallForm", "Ссылки", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox1.setItemText(18, QtGui.QApplication.translate("searchallForm", "Область серии", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox1.setItemText(19, QtGui.QApplication.translate("searchallForm", "Язык", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox1.setItemText(20, QtGui.QApplication.translate("searchallForm", "Дата добавления", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox1.setItemText(21, QtGui.QApplication.translate("searchallForm", "Дата изменения", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox1.setItemText(22, QtGui.QApplication.translate("searchallForm", "Тип публикации", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox1.setItemText(23, QtGui.QApplication.translate("searchallForm", "Реф. код", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox1.setItemText(24, QtGui.QApplication.translate("searchallForm", "УДК", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox1.setItemText(25, QtGui.QApplication.translate("searchallForm", "Zool. Rec.", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox1.setItemText(26, QtGui.QApplication.translate("searchallForm", "ISSN", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox1.setItemText(27, QtGui.QApplication.translate("searchallForm", "ISBN", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox1.setItemText(28, QtGui.QApplication.translate("searchallForm", "Ключевые слова", None, QtGui.QApplication.UnicodeUTF8))
        #self.field_comboBox1.setItemText(27, QtGui.QApplication.translate("searchallForm", "Таксономические ключевые слова", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox1.setItemText(29, QtGui.QApplication.translate("searchallForm", "Номер публикации", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox1.setItemText(30, QtGui.QApplication.translate("searchallForm", "Дата публикации", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox1.setItemText(31, QtGui.QApplication.translate("searchallForm", "Страна публикации", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox1.setItemText(32, QtGui.QApplication.translate("searchallForm", "Номер изд. МПК", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox1.setItemText(33, QtGui.QApplication.translate("searchallForm", "Основной инд. МПК", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox1.setItemText(34, QtGui.QApplication.translate("searchallForm", "Владелец патента", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox1.setItemText(35, QtGui.QApplication.translate("searchallForm", "Реферат", None, QtGui.QApplication.UnicodeUTF8))
        self.field_comboBox1.setItemText(36, QtGui.QApplication.translate("searchallForm", "Полный текст", None, QtGui.QApplication.UnicodeUTF8))
        self.and_comboBox2.setItemText(0, QtGui.QApplication.translate("searchallForm", "И", None, QtGui.QApplication.UnicodeUTF8))
        self.and_comboBox2.setItemText(1, QtGui.QApplication.translate("searchallForm", "ИЛИ", None, QtGui.QApplication.UnicodeUTF8))
        self.and_comboBox2.setItemText(2, QtGui.QApplication.translate("searchallForm", "И НЕ", None, QtGui.QApplication.UnicodeUTF8))
        self.and_comboBox2.setItemText(3, QtGui.QApplication.translate("searchallForm", "ИЛИ НЕ", None, QtGui.QApplication.UnicodeUTF8))
        self.and_comboBox1.setItemText(0, QtGui.QApplication.translate("searchallForm", "И", None, QtGui.QApplication.UnicodeUTF8))
        self.and_comboBox1.setItemText(1, QtGui.QApplication.translate("searchallForm", "ИЛИ", None, QtGui.QApplication.UnicodeUTF8))
        self.and_comboBox1.setItemText(2, QtGui.QApplication.translate("searchallForm", "И НЕ", None, QtGui.QApplication.UnicodeUTF8))
        self.and_comboBox1.setItemText(3, QtGui.QApplication.translate("searchallForm", "ИЛИ НЕ", None, QtGui.QApplication.UnicodeUTF8))
        self.groupParams.setTitle(QtGui.QApplication.translate("searchallForm", "Параметры поиска", None, QtGui.QApplication.UnicodeUTF8))
        
        #self.sel_search_comboBox.setItemText(0, QtGui.QApplication.translate("searchallForm", "Поиск по всей библиотеке", None, QtGui.QApplication.UnicodeUTF8))

        #Пока делаем эти пункты неактивными
        #self.sel_search_comboBox.setEnabled(False)
        #self.sel_search_comboBox.setItemText(1, QtGui.QApplication.translate("searchallForm", "Добавить к найденному", None, QtGui.QApplication.UnicodeUTF8))
        #self.sel_search_comboBox.setItemText(2, QtGui.QApplication.translate("searchallForm", "Поиск в найденном", None, QtGui.QApplication.UnicodeUTF8))
        #self.sel_search_comboBox.setItemText(3, QtGui.QApplication.translate("searchallForm", "Удалить из найденного", None, QtGui.QApplication.UnicodeUTF8))

        self.checkBox_search_results.setText(QtGui.QApplication.translate("searchallForm", "Искать в найденном", None, QtGui.QApplication.UnicodeUTF8))
        #self.checkBox_search_results.setEnabled(False)

        #self.save_queryButton.setText(QtGui.QApplication.translate("searchallForm", "Сохранить запрос", None, QtGui.QApplication.UnicodeUTF8))
        #self.save_queryButton.setEnabled(False)

        #self.load_queryButton.setText(QtGui.QApplication.translate("searchallForm", "Загрузить запрос", None, QtGui.QApplication.UnicodeUTF8))
        #self.load_queryButton.setEnabled(False)
        
        #self.setdef_Button.setText(QtGui.QApplication.translate("searchallForm", "Установить как стандартный", None, QtGui.QApplication.UnicodeUTF8))
        #self.setdef_Button.setEnabled(False)
        
        #self.rest_defButton.setText(QtGui.QApplication.translate("searchallForm", "Восстановить стандартные настройки", None, QtGui.QApplication.UnicodeUTF8))
        #self.rest_defButton.setEnabled(False)

